1. Introduction and Installation


In [1]:
# NumPy is the fundamental package for scientific computing in Python
# It provides support for large, multi-dimensional arrays and matrices

import numpy as np

# Check NumPy version
print("NumPy version:", np.__version__)

NumPy version: 2.3.4


2. Creating Arrays

In [2]:
# Creating arrays from Python lists
# 1D Array (Vector)
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Type:", type(arr1))
print("Data type:", arr1.dtype)
print()

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape:", arr2.shape)  # (rows, columns)
print("Dimensions:", arr2.ndim)
print("Size (total elements):", arr2.size)

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data type: int64

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size (total elements): 6


3. Array Creation Functions


In [3]:
# Creating arrays with built-in functions

# Array of zeros
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros array:\n", zeros)
print()

# Array of ones
ones = np.ones((2, 3))
print("Ones array:\n", ones)
print()

# Array with a specific value
full = np.full((2, 2), 7)
print("Full array (filled with 7):\n", full)
print()

# Identity matrix
identity = np.eye(3)  # 3x3 identity matrix
print("Identity matrix:\n", identity)
print()

# Array with a range of values
range_arr = np.arange(0, 10, 2)  # start, stop, step
print("Range array:", range_arr)
print()

# Linearly spaced array
linspace = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print("Linearly spaced:", linspace)
print()

# Random arrays
random_arr = np.random.random((2, 3))  # values between 0 and 1
print("Random array:\n", random_arr)
print()

# Random integers
random_int = np.random.randint(1, 100, size=(3, 3))  # integers from 1 to 99
print("Random integers:\n", random_int)


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full array (filled with 7):
 [[7 7]
 [7 7]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Range array: [0 2 4 6 8]

Linearly spaced: [0.   0.25 0.5  0.75 1.  ]

Random array:
 [[0.27539817 0.02161368 0.21546467]
 [0.3256759  0.82266403 0.19782193]]

Random integers:
 [[14  6 60]
 [ 3 82 96]
 [76 80 87]]
