## Numpy array and basics
learn about numpy

In [44]:
import numpy as np
print(np.__version__)

2.3.4


#### Creating array

In [45]:
arr_1d = np.array([1,2,3,4,5]) # array take one array as parameter
print("1D array: ", arr_1d)

# arr_2d = np.array([1,2,3],[4,5,6]) # Error
arr_2d = np.array([[1,2,3],[4,5,6]]) 
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


#### List vs numpy array

In [46]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list*2)

np_array = np.array([1,2,3])
print("Python array multiplication: ", np_array*2)

import time
start = time.time()
py_list = [ i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy array operation time: ", time.time() - start)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.09409499168395996

 Numpy array operation time:  0.0061986446380615234


#### Creating array from scratch

In [47]:
zeros = np.zeros((3,4))
print("Zero array: \n", zeros)

ones = np.ones((2,4))
print("Ones array: \n", ones)

full = np.full((2,3),7)
print("full array: \n",full)

# sequence = np.arange(15) #  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
sequence = np.arange(1,20,2)
print("Sequence array: \n", sequence)

Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]]
Sequence array: 
 [ 1  3  5  7  9 11 13 15 17 19]


#### Vector, Matrix and Tensor


In [48]:
vector = np.array([1,2,3,4,5,6,7,8])
print("Vector: \n", vector)
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor)


Vector: 
 [1 2 3 4 5 6 7 8]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Array properties


In [49]:
vector = np.array([1,2,3,4,5,6,7,8])
matrix = np.array([[1,2,3],
                   [4,5,6]])
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])

print("Shape ", tensor.shape)
print("Dimension ", tensor.ndim)
print("Size ", tensor.size)
print("DType ", tensor.dtype)

Shape  (2, 2, 2)
Dimension  3
Size  8
DType  int64


#### Array Reshaping


In [50]:

arr = np.arange(12)
reshaped = arr.reshape((3,4))
print("Reshaped array: \n", reshaped)

flatten_arr = reshaped.flatten()
print("flatten array: \n", flatten_arr)
# print("Reshaped array: \n", reshaped)


# ravel (returns view, instead of copy)
ravel_arr = reshaped.ravel()
print("ravel array: \n", ravel_arr)
# print("Reshaped array: \n", reshaped)

transpose_arr = reshaped.T
print("Transpose array: \n", transpose_arr)


Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatten array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
