#### Numpy array operations

In [ ]:
import numpy as np

In [25]:
arr = np.arange(0,9)
print("Array: ",arr)
print("Slicing array : ", arr[:4])
print("Slicing array with step: ", arr[:4:2])
print("Negative indexing : ", arr[-2])


Array:  [0 1 2 3 4 5 6 7 8]
Slicing array :  [0 1 2 3]
Slicing array with step:  [0 2]
Negative indexing :  7


In [39]:
re_arr = arr.reshape(3,3)
print("Reshaped array: \n", re_arr)

print("Specific element: ",re_arr[1,2])
print("Entire row: ",re_arr[1])
print("Entire column: ",re_arr[:,1])

print("sub-array: ", re_arr[:2,:2])
print("sub-array: ", re_arr[1:,1:])


Reshaped array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Specific element:  5
Entire row:  [3 4 5]
Entire column:  [1 4 7]
sub-array:  [[0 1]
 [3 4]]
sub-array:  [[4 5]
 [7 8]]


#### Sorting


In [48]:
unsorted = np.array([3,4,1,7,2,5,6])
print("Sorted array: ", np.sort(unsorted))

unsorted_2d = np.array([[32,12,43],[34,52,42],[12,27,35]])
print("Sorting 2D array column wise: ", np.sort(unsorted_2d, axis=0))
print("Sorting 2D array row wise: ", np.sort(unsorted_2d, axis=1))

Sorted array:  [1 2 3 4 5 6 7]
Sorting 2D array column wise:  [[12 12 35]
 [32 27 42]
 [34 52 43]]
Sorting 2D array row wise:  [[12 32 43]
 [34 42 52]
 [12 27 35]]


#### filter

In [57]:
numbers = np.arange(1,11)
even_numbers = numbers[numbers % 2 == 0]
print(numbers[[1,4,5,6,9]])
print(numbers % 2 == 0)
print(even_numbers)

[ 2  5  6  7 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
